[versions]
minecraft = "1.21.1"
fabric-loader = "0.16.9"
fabric-api = "0.107.0+1.21.1"
cobblemon = "1.6.0+1.21.1-SNAPSHOT"
gooeylibs = "3.1.0-1.21.1-SNAPSHOT"


# Plugins
fabric-loom = "1.8-SNAPSHOT"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
cobblemon-fabric = { module = "com.cobblemon:fabric", version.ref = "cobblemon" }
gooeylibs-fabric = {module= "ca.landonjw.gooeylibs:fabric-api-repack", version.ref = "gooeylibs"}

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
